### ISSUE TITLE
spacer.gif is missing

### ISSUE THREAD

**Issue by pierre-b** [g13nn/Email-Framework#1]
Hi Glenn,

First, thank you for sharing your work with us !

In the boilerplate you add an image "images/spacer.gif" but the file is not in the repo, is this normal ?

**Comment by g13nn** [comment]
Hello Pierre,

Well spotted! It's my first time using GitHub so didn't really know how to upload the image to the repo I'll do some research today and get it added.

**Comment by pierre-b** [comment]
You can use the git GUI wich allows you to track changes in your git folders and commit them with a button. http://git-scm.com/downloads/guis

**Comment by g13nn** [comment]
Hello Pierre,

Thank you for the information, i have now added the images folder & spacer.gif image to the repo.
