### ISSUE TITLE
Adapting to mosaico editor

### ISSUE THREAD

**Issue by bago** [g13nn/Email-Framework#10]
We just pushed http://github.com/voidlabs/mosaico an email template editor.
Would you mind if we adapt your template to be used inside mosaico?
Can we redistribute the adaptation under the GPL license?

**Comment by g13nn** [comment]
Hey Bago, I stumbled across your editor earlier today too, its very functional and i like it, of course you can use the template.  Just a reference back to the Email Framework would be appreciated. Thanks

**Comment by bago** [comment]
Can you explain me the relationship between modules/module-master.html , templates/newsletter-template.html and templates/stamplia.html ? They seems to be unrelated, but before trying to convert one, I'd like to understand this better...

**Comment by g13nn** [comment]
Hey Bago,  Modules master is a template which contains all modules built for this framework(This is on-going and get's updated with new modules when i have time).  Template is just a random template i put together using the email framework & Stamplia is a template built using the email framework which makes use of all modules available on the Stamplia builder.

**Comment by bago** [comment]
Let me understand the "wrapper widths": I see the psd grid with 100%/800/640 widths.
In master template I see every module is 640 but the navigation modules that are 100%, but in newsletter-template I see most modules are 800px (but I also see weird code where MSO conditional comments still says 640).

So, I'm trying to understand what is the "idea" of the framework: maybe something similar to this:
1) every module can be "fixed width" or "full width"
2) the template have a width that is 640 by default, but you can make it bigger (e.g: 800px in your example).

Right?

In this case I should simply add
1) A global variable to define the template width (min 640px)
2) A "per module" variable to define if it is a full width module or a fixed width module.
right?

But I also see other differences: 
for example the 2 columns img/title/text/button module in the master template have 290px wide images while the newsletter-template has 280px wide images.

If you don't care about details I'll take my choices while porting the template, but before doing this, I wanted to hear your voice, so that the final template will respect your original idea as much as possibile.

**Comment by g13nn** [comment]
Hey Bago,

That's correct each module/grid has an outer wrapper of 640px and an inner container of 600px.  The 640 width can be changed to 800px or 100% or any width you desire. The 640 wrapper is mainly there for Yahoo and mobile views.  For Yahoo it allows us to ensure our blocks center align and for mobile it gives us some padding.

Apologies there maybe some differences going between the module master, template & stamplia each of these are setup different but i've still tried to use the base of the email framework where it will let me.

I care about the details and i hope i have cleared things up here, if not please shout.  I'd say go ahead and use the email framework how you feel comfortable and if you have any problems please do let me know.  Keep up the good work!
