### ISSUE TITLE
The Hybrid Coding approach

### ISSUE THREAD

**Issue by g13nn** [g13nn/Email-Framework#12]
So currently this email framework does not support "The Hybrid Coding approach".  Currently it uses a 1px gif at the top of the email.  This will force android clients to display the desktop version of the template.  

It would be good to build this into the framework.  We could create a folder and re-do each part of the framework so we can still keep the old setup, or just build it straight into the framework as is...

Resources : 
- http://labs.actionrocket.co/the-hybrid-coding-approach
- http://labs.actionrocket.co/the-hybrid-coding-approach-2
- https://github.com/fcarneiro/tedc15_template
- http://webdesign.tutsplus.com/tutorials/creating-a-future-proof-responsive-email-without-media-queries--cms-23919

**Comment by Creativenauts** [comment]
Good idea. I'm not a fan of having ghosted tables in emails, just really makes it confusing for others in my opinion. I still just go the route of doing display: block on TDs. Hopefully android and gmail get it together soon, because this method is easy in my opinion.

**Comment by g13nn** [comment]
Hybrid grid examples now added.
