### ISSUE TITLE
Link to Documentation is dead

### ISSUE THREAD

**Issue by superfine** [g13nn/Email-Framework#17]
Documentation on http://emailframe.work/ is down :- (

> The server at emailframe.work can't be found, because the DNS lookup failed. DNS is the network service that translates a website's name to its Internet address. This error is most often caused by having no connection to the Internet or a misconfigured network. It can also be caused by an unresponsive DNS server or a firewall preventing Google Chrome from accessing the network.

**Comment by g13nn** [comment]
It's online - http://www.downforeveryoneorjustme.com/emailframe.work

**Comment by superfine** [comment]
It's online:
![2016-04-22 14_17_24-http___emailframe work_ is not available](https://cloud.githubusercontent.com/assets/745785/14741223/0a03900a-0895-11e6-9518-11333ca96bb7.png)

**Comment by g13nn** [comment]
I've had reports that some users cannot access the site due to the .work domain name.  I will work on getting mirror websites online so that you can all access this.  Please bare with me.

**Comment by gnanet** [comment]
Hi, the docs website also mention a PSD which is missing

> 
> Designers
> 
> Included in this framework is a PSD containing all widths and guidelines for designing emails templates with the email framework in mind.
> 
>

**Comment by g13nn** [comment]
Hey gnanet,

I'm currently making updates on this framework.  The PSD was deleted a few days ago.  If you would like the PSD you can grab a copy of it here - https://github.com/g13nn/Email-Framework/tree/7b6b653e09b0033dd8562d28cf78848fc29ca17f/PSD

**Comment by gnanet** [comment]
Thank you.
