### ISSUE TITLE
Use <code> tag instead of <span style="…">

### ISSUE THREAD

**Issue by ricardozea** [g13nn/Email-Framework#18]
Not an issue per se, but I noticed that you had to add a space to a non-breaking space HTML entity in order for the characters to actually appear on the page, otherwise it would've looked like an empty element.

It looks like this `& nbsp;` instead of like this `&nbsp;`

![screenshot - 2_19_2016 9_49_38 pm](https://cloud.githubusercontent.com/assets/1656481/13194072/23d20be2-d753-11e5-94be-f83f3674ab75.png)

Why don't you just use the `<code>` tag instead of a `<span>` with inline styles? 

Greate job with this email framework +1.

**Comment by g13nn** [comment]
Hey ricardozea,

Apologises for missing this.  Yes that is a little silly.  I will make this update within the coming weeks when i update the documentation website.

**Comment by ricardozea** [comment]
💯
