### ISSUE TITLE
Deleted content

### ISSUE THREAD

**Issue by Poltuu** [g13nn/Email-Framework#19]
Hello,

I've been planning on using your great templates on my project.
But I'm seeing a lot of content deleted in the past 5 days: could you tell me why ?

Thanks

**Comment by g13nn** [comment]
Hey Poltuu,

I have deleted modules & templates as i plan to make a few needed structural changes to the framework.  This should be completed within the next few weeks.

Thanks
Glenn

**Comment by radium226** [comment]
I just came across your framework and I am also very interested in using it. 

Do you plan to push your refactoring soon? Just for me to know, what are you planning to do?

Thank you!
Radium.

**Comment by g13nn** [comment]
Hello Radium226, 

Thanks for checking out the email framework.  My plans are to keep everything very much the same.  I'm just going to be adding a few other ways of coding emails.  

My target is : Responsive, Hybrid, Mobile Aware & Fluid. 

So this way the email framework keeps the responsive way of coding that so many of are used to but also include some new coding standards to support the tricky clients like gmail & android.

Each one will have its own folder to allow you to pick a solution that best suites you're needs and begin coding as you normally would when using the email framework.

I will also add example modules and templates as before for each.

I hope to push these changes very soon!

**Comment by radium226** [comment]
I just saw you pushed your changes! I didn't have the time to look at it in detail, but is the documentation up to date? If not, I will do a `git clone` tonight in order to try it  :smile: 

Have a great day, 
Radium.

**Comment by g13nn** [comment]
Hey Radium226,

I have pushed a few changes to the framework, this has not been updated on the documentation site just yet.  I've only made a few adjustments, no hybrid, mobile aware or fluid options just yet.  

I will try to get around to changing the website ASAP, but not much has changed to be honest.
