### ISSUE TITLE
Issue with grids on Gmail App on Android?

### ISSUE THREAD

**Issue by tbuteler** [g13nn/Email-Framework#21]
The mobile version doesn't seem to be taking effect on Gmail for Android. All other mobile versions work fine, except this one. I suspected I had done something wrong, but then copied and pasted your exact "responsive-grid-master.html" and got the same result.

Test on Litmus:

<img width="358" alt="screen shot 2017-01-04 at 10 47 57" src="https://cloud.githubusercontent.com/assets/330375/21640143/cf04e3ea-d26b-11e6-8e50-6f93b181a178.png">

**Comment by g13nn** [comment]
Hey tbuteler,

Thank you for spotting this i have updated the hybrid examples, give them a try now.

What the grids do :

"responsive-grid-master.html" displays the desktop version for this client.
"fluid-grid-master.html" just stays the same.
"hybrid-grid-master.html" will stack on this device and others.
