### ISSUE TITLE
Outlook 2013 - Images

### ISSUE THREAD

**Issue by g13nn** [g13nn/Email-Framework#6]
Some images appear to be squashed in Outlook 2013.  Currently looking into this. 

Fix : Add line-height & height to style on surrounding td

**Comment by proofgavlar** [comment]
I had the same issue.

I found simply adding style="height: auto;" to the surrounding td fixed it for me.

**Comment by g13nn** [comment]
Nice, didn't know that one, i also found if you strip the style tag of the surrounding td and set a width and height on your image then it will render correctly in Outlook (2013).
