### ISSUE TITLE
Font family should be defined for table cells

### ISSUE THREAD

**Issue by marchenko1985** [g13nn/Email-Framework#7]
Outlook overrides table cell font family if one is not defined in cell styles.

So in your grid examples every cell should be replaced with something like this:

``` html
<td width="600" class="mobile" style="font-family: Arial; font-size:12px; line-height:18px;">
    Grid One
</td>
```

**Comment by g13nn** [comment]
Hi Mac2000,

Your completely correct here, i have now updated the grid & master template files.  I will update the documentation website later to include this too.

**Comment by marchenko1985** [comment]
If you wish I can help you with pull request on holidays to fix that

**Comment by g13nn** [comment]
Hi Mac2000,  Thanks for offering to help out.  I will be able to make the changes to the documentation page later on when back from work, wont take long at all.  If you have any ideas to add to the email framework please do let me know, i'd love to hear them.  Thanks again!

**Comment by g13nn** [comment]
I have now updated the documentation page, Thanks again Mac2000 for pointing this out to me!

I have added this to the content block code too, and if you don't use the content block then at least we can rely on the grid alone to render the font.
